In [18]:
# Creating Numpy arrays 

import numpy as np

one = np.ones((2, 3))
print(one)

print()

zero = np.zeros((2, 3))
print(zero)

print()

even = np.arange(0, 10, 2)
print(even)

print()

random_array = np.random.randint(0, 10, (5, 3))
print(random_array)

[[1. 1. 1.]
 [1. 1. 1.]]

[[0. 0. 0.]
 [0. 0. 0.]]

[0 2 4 6 8]

[[5 6 4]
 [6 1 4]
 [5 8 0]
 [1 5 8]
 [6 8 6]]
