In [11]:
import numpy as np

np.random.seed(0)  

mat1 = np.random.randint(10, size=(3, 3))
mat2 = np.random.randint(10, size=(3, 3))

print(mat1 * mat2)

print()

print(np.dot(mat1, mat2))

print()

print(mat1.dot(mat2))

print()

print(mat1 @ mat2)

[[20  0 18]
 [24 56  9]
 [18 35 14]]

[[ 38  56  51]
 [122 140  88]
 [ 64  75  37]]

[[ 38  56  51]
 [122 140  88]
 [ 64  75  37]]

[[ 38  56  51]
 [122 140  88]
 [ 64  75  37]]
