In [2]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [3]:
# Create a 1-dimensional NumPy array using np.array()
arr1 = np.array([1, 2, 3, 4, 5])

In [4]:
# Create a 2-dimensional NumPy array using np.array()
arr2 = np.array([[1, 2, 3],
                [4, 5, 6]])

In [5]:
# Create a 3-dimensional NumPy array using np.array()
arr3 = np.array([[[1, 2, 3],
                  [4, 5, 6]],
                 
                 [[7, 8, 9],
                  [10, 11, 12]]])

In [6]:
# Attributes of 1-dimensional array
print("1D Array")
print("Shape:", arr1.shape)
print("Dimensions:", arr1.ndim)
print("Data Type:", arr1.dtype)
print("Size:", arr1.size)
print("Type:", type(arr1))

1D Array
Shape: (5,)
Dimensions: 1
Data Type: int64
Size: 5
Type: <class 'numpy.ndarray'>


In [7]:
# Attributes of 2-dimensional array
print("\n2D Array")
print("Shape:", arr2.shape)
print("Dimensions:", arr2.ndim)
print("Data Type:", arr2.dtype)
print("Size:", arr2.size)
print("Type:", type(arr2))


2D Array
Shape: (2, 3)
Dimensions: 2
Data Type: int64
Size: 6
Type: <class 'numpy.ndarray'>


In [8]:
# Attributes of 3-dimensional array
print("\n3D Array")
print("Shape:", arr3.shape)
print("Dimensions:", arr3.ndim)
print("Data Type:", arr3.dtype)
print("Size:", arr3.size)
print("Type:", type(arr3))


3D Array
Shape: (2, 2, 3)
Dimensions: 3
Data Type: int64
Size: 12
Type: <class 'numpy.ndarray'>


In [9]:
# Import pandas and create a DataFrame out of one of the arrays
import pandas as pd

df = pd.DataFrame(arr2)
print("\nDataFrame:")
print(df)


DataFrame:
   0  1  2
0  1  2  3
1  4  5  6


In [10]:
# Create an array of shape (10, 2) with only ones
ones_array = np.ones((10, 2))
print("\nOnes Array:")
print(ones_array)


Ones Array:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [11]:
# Create an array of shape (7, 2, 3) of only zeros
zeros_array = np.zeros((7, 2, 3))
print("\nZeros Array:")
print(zeros_array)


Zeros Array:
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [12]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0, 100, 3)
print("\nRange Array:")
print(range_array)


Range Array:
[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]


In [13]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_int_array = np.random.randint(0, 10, size=(7, 2))
print("\nRandom Integer Array:")
print(random_int_array)


Random Integer Array:
[[1 8]
 [0 8]
 [1 4]
 [8 1]
 [0 7]
 [9 1]
 [2 4]]


In [14]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_float_array = np.random.random((3, 5))
print("\nRandom Float Array:")
print(random_float_array)


Random Float Array:
[[0.961769   0.9337218  0.3466115  0.73233904 0.14274166]
 [0.39745468 0.51423235 0.12497365 0.32937867 0.59405814]
 [0.98128419 0.68823151 0.81556296 0.02541718 0.16505539]]


In [15]:
# Set the random seed to 42
np.random.seed(42)

In [16]:
# Create a random array of numbers between 0 & 10 of size (4, 6)
random_seeded_array = np.random.randint(0, 10, size=(4, 6))
print("\nRandom Seeded Array:")
print(random_seeded_array)


Random Seeded Array:
[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [17]:
# Run again
np.random.seed(42)
random_seeded_array2 = np.random.randint(0, 10, size=(4, 6))
print("\nRandom Seeded Array Again:")
print(random_seeded_array2)


Random Seeded Array Again:
[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [18]:
# Same numbers because setting the same seed reproduces the same random sequence.

# Create an array of random numbers between 1 & 10 of size (3, 7)
rand_arr = np.random.randint(1, 10, size=(3, 7))
print("\nRandom Array:")
print(rand_arr)


Random Array:
[[9 1 3 7 4 9 3]
 [5 3 7 5 9 7 2]
 [4 9 2 9 5 2 4]]


In [19]:
# Find the unique numbers
print("\nUnique Numbers:")
print(np.unique(rand_arr))


Unique Numbers:
[1 2 3 4 5 7 9]


In [20]:
# Find the 0'th index
print("\n0th Index:")
print(rand_arr[0])


0th Index:
[9 1 3 7 4 9 3]


In [21]:
# Get first 2 rows
print("\nFirst 2 Rows:")
print(rand_arr[:2])


First 2 Rows:
[[9 1 3 7 4 9 3]
 [5 3 7 5 9 7 2]]


In [22]:
# Get first 2 values of first 2 rows
print("\nFirst 2 Values of First 2 Rows:")
print(rand_arr[:2, :2])


First 2 Values of First 2 Rows:
[[9 1]
 [5 3]]


In [23]:

# Create a random array and ones array both size (3,5)
random_array = np.random.randint(0, 10, size=(3, 5))
ones_array_35 = np.ones((3, 5))

# Add the two arrays together
print("\nAddition:")
print(random_array + ones_array_35)

# Create another array of ones of shape (5,3)
ones_53 = np.ones((5, 3))

# Try addition
# random_array + ones_53
# Error because shapes (3,5) and (5,3) are not compatible for broadcasting.

# Fix:
ones_35 = np.ones((3, 5))

# Subtract
print("\nSubtraction:")
print(random_array - ones_35)

# Multiply
print("\nMultiplication:")
print(random_array * ones_35)

# Power of 2
print("\nPower using **")
print(random_array ** 2)

# Power using np.square()
print("\nPower using np.square()")
print(np.square(random_array))


Addition:
[[ 7.  8.  3.  1.  4.]
 [ 2.  8.  4.  2.  6.]
 [ 6. 10.  4.  6.  2.]]

Subtraction:
[[ 5.  6.  1. -1.  2.]
 [ 0.  6.  2.  0.  4.]
 [ 4.  8.  2.  4.  0.]]

Multiplication:
[[6. 7. 2. 0. 3.]
 [1. 7. 3. 1. 5.]
 [5. 9. 3. 5. 1.]]

Power using **
[[36 49  4  0  9]
 [ 1 49  9  1 25]
 [25 81  9 25  1]]

Power using np.square()
[[36 49  4  0  9]
 [ 1 49  9  1 25]
 [25 81  9 25  1]]


In [24]:
# Mean
print("\nMean:", np.mean(random_array))

# Maximum
print("Max:", np.max(random_array))

# Minimum
print("Min:", np.min(random_array))

# Standard deviation
print("Standard Deviation:", np.std(random_array))

# Variance
print("Variance:", np.var(random_array))

# Reshape to (3,5,1)
reshaped = random_array.reshape(3, 5, 1)
print("\nReshaped:")
print(reshaped)

# Transpose
transposed = random_array.T
print("\nTransposed:")
print(transposed)


Mean: 3.8666666666666667
Max: 9
Min: 0
Standard Deviation: 2.578543947441829
Variance: 6.648888888888889

Reshaped:
[[[6]
  [7]
  [2]
  [0]
  [3]]

 [[1]
  [7]
  [3]
  [1]
  [5]]

 [[5]
  [9]
  [3]
  [5]
  [1]]]

Transposed:
[[6 1 5]
 [7 7 9]
 [2 3 3]
 [0 1 5]
 [3 5 1]]


In [25]:
# Transpose swaps rows and columns.

# Create arrays for dot product
a = np.random.randint(0, 10, size=(3, 3))
b = np.random.randint(0, 10, size=(3, 2))

print("\nDot Product:")
print(np.dot(a, b))

# Create two arrays of size (4,3)
c = np.random.randint(0, 10, size=(4, 3))
d = np.random.randint(0, 10, size=(4, 3))

# np.dot(c, d) -> Error
# Because inner dimensions do not match.

# Fix using transpose
print("\nDot Product After Transpose:")
print(np.dot(c, d.T))

# Transpose changes d from (4,3) to (3,4),
# allowing (4,3) dot (3,4).


Dot Product:
[[ 88 117]
 [100 123]
 [ 89 127]]

Dot Product After Transpose:
[[ 24 102  96   8]
 [ 16 114 106  63]
 [ 22 123 114  56]
 [  8  60  58   7]]


In [26]:
# Create two arrays of same shape
arr_a = np.random.randint(0, 10, size=(3, 3))
arr_b = np.random.randint(0, 10, size=(3, 3))

# Compare with >
print("\nGreater Than:")
print(arr_a > arr_b)

# Compare with >=
print("\nGreater Than or Equal:")
print(arr_a >= arr_b)

# Elements greater than 7
print("\nElements > 7:")
print(arr_a[arr_a > 7])

# Equal elements
print("\nEqual Elements:")
print(arr_a == arr_b)


Greater Than:
[[ True  True  True]
 [ True False False]
 [False False False]]

Greater Than or Equal:
[[ True  True  True]
 [ True False False]
 [False False False]]

Elements > 7:
[]

Equal Elements:
[[False False False]
 [False False False]
 [False False False]]


In [27]:
# Sort array
print("\nSorted Array:")
print(np.sort(arr_a))

# Sort indexes
print("\nSorted Indexes:")
print(np.argsort(arr_a))


Sorted Array:
[[6 6 7]
 [2 4 7]
 [0 2 5]]

Sorted Indexes:
[[0 1 2]
 [1 0 2]
 [2 1 0]]


In [ ]:
# Index of maximum value
print("\nIndex of Maximum:")
print(np.argmax(arr_a))

# Index of minimum value
print("\nIndex of Minimum:")
print(np.argmin(arr_a))

# Indexes of max values along axis=1
print("\nMax Index Along Axis=1:")
print(np.argmax(arr_a, axis=1))

# Indexes of min values along axis=0
print("\nMin Index Along Axis=0:")
print(np.argmin(arr_a, axis=0))

In [ ]:
# Create normally distributed random numbers
normal_array = np.random.randn(10)
print("\nNormally Distributed Numbers:")
print(normal_array)

# Create 10 evenly spaced numbers between 1 and 100
evenly_spaced = np.linspace(1, 100, 10)
print("\nEvenly Spaced Numbers:")
print(evenly_spaced)