In [10]:
import numpy as np


## Reshape an array
a1 = np.array([1, 2, 3, 4, 5, 6])
print(a1.shape)

print()

reshape_a1 = a1.reshape(2, 3)
print(reshape_a1)

print() 

print(reshape_a1.shape)

print()

## Transpose an array

a2 = np.array([[1, 2, 3], [4, 5, 6]])
print(a2.shape)

print()

transpose_a2 = a2.T
print(transpose_a2)
print(transpose_a2.shape)



(6,)

[[1 2 3]
 [4 5 6]]

(2, 3)

(2, 3)

[[1 4]
 [2 5]
 [3 6]]
(3, 2)
