In [3]:
import numpy as np 

a1 = np.array([1, 2, 3, 9, 3, 7, 0])

print(np.sort(a1))

[0 1 2 3 3 7 9]


In [4]:
print(np.argsort(a1))

[6 0 1 2 4 5 3]


In [5]:
print(np.argsort(a1)[::-1])

[3 5 4 2 1 0 6]


In [6]:
print(np.argmax(a1))
print(np.argmin(a1))

3
6
